### ISSUE TITLE
Review Program

### ISSUE THREAD

**Issue by hengkyramadhano** [evo3cx/gunadarma#32]
@evo3cx kak Reza bisa tolong bantu kirim source code html css javascript yang dari website kemaren, cuma buat review aja kak.

**Comment by reza-putra** [comment]
baru lihat, ada di github source code nya koq, hmm nanti saya cek dulu dmn branch nya @hengkyramadhano

**Comment by evo3cx** [comment]
https://github.com/evo3cx/gunadarma/tree/master/chapter2/step1%20-%20Header

@hengkyramadhano

**Comment by reza-putra** [comment]
@hengkyramadhano 

ini lengkap nya : https://github.com/evo3cx/gunadarma/tree/master/chapter2

disini ada folder : 
   

1. step1-header (  ini folder source code yang kemarin kita bahas )
2. step2-body & step3-feature ( ini folder source code untuk body nya, akan di bahas minggu depan)

ini bisa di bagikan keteman2 yang lain informasinya

**Comment by hengkyramadhano** [comment]
@evo3cx Terima kasih kak, akan saya informasikan ke teman2
