### ISSUE TITLE
Nanya dong kak

### ISSUE THREAD

**Issue by erlanggasa1** [evo3cx/gunadarma#37]
Kak reza ini saya ada tugas yang sedang saya buat, ini filenya. 
[ibu_nur.zip](https://github.com/evo3cx/gunadarma/files/856729/ibu_nur.zip)

yang mau saya tanyain, 
1. Gimana buat kalender dan bisa nampilin data pada tanggal yang kita pilih saja?
2. Kalo data banyak gimana membuat limit datanya dengan bikin pilihan halaman dibawahnya misal halaman 1,2,3 dst. 

kurang lebih mau kaya gini kak, 
![capture1 copy](https://cloud.githubusercontent.com/assets/25262817/24127468/6de96cb6-0e07-11e7-80e7-71744141717e.png)

terimakasih kak sebelumnya

**Comment by reza-putra** [comment]
> 1. Gimana buat kalender dan bisa nampilin data pada tanggal yang kita pilih saja?

saya kurang paham dengan pertanyaanya? maksudnya dengan membuat kalendar dengan data yang di pilih itu seperti apa? apakah yang di maksud kamu itu, ketika saya pilih tanggal 21 maret maka data yang keluar hanya pada hari itu saja?


> 2. Kalo data banyak gimana membuat limit datanya dengan bikin pilihan halaman dibawahnya misal halaman 1,2,3 dst.

bisa pakai offset pada query nya, 

saya belum lihat code yang kamu kirim, coba codenya jangan di attachment di sini, di push saja code nya ke github jadi saya mudah untuk mereview nya.

di pisahkan foldernya dengan materi pertemuan agar rapih yah,

**Comment by erlanggasa1** [comment]
1. iya kak bener maksudnya seperti itu.
2. oke kak saya kirim

**Comment by erlanggasa1** [comment]
Kak udah saya push filenya

**Comment by reza-putra** [comment]
Sudah kamu push branch nya apa? Coba kamu kirimkan link branch nya

**Comment by erlanggasa1** [comment]
https://github.com/erlanggasa1/ibu_nur

maaf kak kurang paham saya nge push ke sini

**Comment by reza-putra** [comment]
okey nanti malam saya coba check yah,

**Comment by reza-putra** [comment]
@erlangga bagaimana jika masalah ini di bahas ketika kelas nanti, sepertinya seru jika masalahnya di bahas sama2 jadi pada mengerti semua

**Comment by erlanggasa1** [comment]
Oke kak gapapa

**Comment by erlanggasa1** [comment]
kira kira gunain apa ya kak untuk input tanggalnya?

**Comment by reza-putra** [comment]
maaf baru balas erlangga, saya hari minggu off dari kegiataan,

ini beberapa bagian yg saya ubah pada index.php kamu
`

     <?php

    $query = "SELECT * FROM transaksi";

    // jika user meminta transaksi dengan tanggal yang di tentukan
    // ubah $query sql nya
    if ( isset($_GET["date"])) {
      $query = "SELECT * FROM transaksi where tanggal_transaksi = '" .  $_GET["date"] ."'";
    }
    echo $query;
		$result = mysqli_query($connect, $query) or die("query gagal");

    // Jika transaksi tidak di temkan beri pesan ke user
    if($result->num_rows == 0){
      echo '<tr>
    		<td colspan="7"> Maaf transaksi tidak di temukan </td>
      </tr>';
    }
    ?>

    <?php
		//$no = 0;
		while ($buff = mysqli_fetch_array($result))
		{
		//$no++;
	?>

	<tr>
		<td><?php echo $buff['kode_transaksi']; ?></td>
		<td><?php echo $buff['tanggal_transaksi']; ?></td>
		<td><?php echo $buff['nama_pembeli']; ?></td>
		<td><?php echo $buff['total_harga']; ?></td>
		<td><?php echo $buff['jenis_transaksi']; ?></td>

		<td><a href="edit.php?kode_transaksi=<?php echo $buff['kode_transaksi']; ?>">Edit</a></td>
		<td><a href="hapus.php?kode_transaksi=<?php echo $buff['kode_transaksi']; ?>">Hapus</a>
               </td>
	</tr>
	<?php
	}
	mysqli_close($connect);
	?>
	</table>

	<form action='tambah.html' method='POST'>
		<table align="center">
 			<tr>
 				<td> <input type='submit' name='tambah' value='Tambah Transaksi'> </td>
 			</tr>
		</table>
	</form>
`

**Comment by reza-putra** [comment]
@erlanggasa1 silahkan di lakukan `git pull` lalu cek pada direktory ibu_nur_erlangga

**Comment by reza-putra** [comment]
Erlangga tolong ingatkan ke teman2 nya minggu depan persentasi aplikasi nya

Point point yang ada pada persentasi nya meliputi

- Latar belakang pembuatan aplikasi
- Tujuan aplikasi
- Prototype

Tolong di ingatkan yah

Pada tanggal 26 Mar 2017 10.42 AM, "erlanggasa1" <notifications@github.com>
menulis:

**Comment by erlanggasa1** [comment]
Iya kak sudah di beritahukan, terimakasih kak bantuannya, kalo untuk no 2 pake, limit sama pagenation yaa?

**Comment by reza-putra** [comment]
> Kalo data banyak gimana membuat limit datanya dengan bikin pilihan halaman dibawahnya misal halaman 1,2,3 dst.

untuk yang ini bisa pakai offset pada query seperti yang kemarin saya bilang,
[query offset](https://www.w3schools.com/php/php_mysql_select_limit.asp)

@erlanggasa1
